version: '3.3'
services:
  mongo:
    image: 'mongo:latest'
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  application:
    depends_on:
      - mongo
    container_name: 'nestjs_api'
    image: 'node:16.17.0'
    user: 'node'
    working_dir: '/home/node/app'
    restart: 'unless-stopped'
    env_file: './.env'
    environment:
      MONGODB_HOST: mongo
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    command: 'npm run start'

volumes:
  mongodata: